name: 'moulinette'
description: 'Check if the current day is a success or not'
branding:
  color: blue
  icon: check
inputs:
  pr_name:
    required: false
    description: get the pr name
    default: '${{ github.event.pull_request.name }}'
runs:
  using: 'node12'
  main: 'index.js'
